name: "tiktok"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2022-05-15"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "info"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: xxxx
  port: xxxx
  user: "xxxx"
  password: "xxx"
  dbname: "tiktok"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: xxxx
  port: xxxx
  password: "xxxx"
  db: 0
  pool_size: 100

usersrv:
  host: 127.0.0.1
  port: 9001